### ISSUE TITLE
Time bar not available

### ISSUE THREAD

**Issue by AadeIT** [amzn/amazon-s3-gst-plugin#27]
hi all，
this is a great project.
I 'm using s3sink, Mp4 works, MKV can store and play, but the time bar cannot jump
this is my pipline
`gst-launch-1.0 -e rtspsrc location=rtsp://admin:123456@ip  ! parsebin ! h264parse !  matroskamux  offset-to-zero=true  ! s3sink aws-sdk-use-http=true aws-sdk-endpoint=ip:port aws-sdk-s3-sign-payload=false bucket=test key=video5.mkv`

result
![image](https://user-images.githubusercontent.com/46584679/175080462-ff4bd910-a3fa-4aba-a92a-e54d6a9ab61f.png)

We look forward to your reply，thank you

**Comment by smthsm** [comment]
Hi @AadeIT, apologies for not getting back to you sooner. Did you manage to solve your issue with the missing timebar? If not, a good next step would be to confirm whether the timebar works when writing the MKV file directly to disk (by swapping out the `s3sink` for a `filesink`).

Let us know if you would still like assistance in debugging the issue, and we can look into it further.

**Comment by smthsm** [comment]
I'm going to close this issue out for now. Please feel free to re-open it or raise a new one if you'd still like help debugging the missing time bar.
