### ISSUE TITLE
Having issue with aws-cpp-sdk-s3 while running meson build

### ISSUE THREAD

**Issue by faisalapp1** [amzn/amazon-s3-gst-plugin#28]
I am having issue while setting up the plugin when i run meson build it gives me these logs
The Meson build system
Version: 0.53.2
Source dir: /home/faisal/gst/amazon-s3-gst-plugin
Build dir: /home/faisal/gst/amazon-s3-gst-plugin/build
Build type: native build
Project name: amazon-s3-gst-plugin
Project version: 0.1.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency glib-2.0 found: YES 2.64.6
Run-time dependency gstreamer-1.0 found: YES 1.16.2
Run-time dependency gstreamer-base-1.0 found: YES 1.16.2
Run-time dependency gstreamer-check-1.0 found: YES 1.16.2
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency aws-cpp-sdk-s3 found: NO (tried pkgconfig and cmake)

meson.build:20:0: ERROR: Dependency "aws-cpp-sdk-s3" not found, tried pkgconfig and cmake

I am not sure about aws sdk while i am setting it up correctly or not,Please let me know about the steps of setting aws sdk for s3. Thanks

**Comment by dmitryashutov** [comment]
Hi @faisalapp1. You need to install [AWS SDK for C++](https://github.com/aws/aws-sdk-cpp#aws-sdk-cpp). It's not necessary to install all the service packages, just s3 and sts. I guided with this [documentation page](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html)

**Comment by smthsm** [comment]
Hi @faisalapp1, apologies for not getting back to you sooner. Have you had a chance to try out the [instructions](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html) linked in previous comment? (thanks for that @dmitryashutov)

Let us know if you're still having issues with the build and we can look into it further.

**Comment by smthsm** [comment]
I'm going to close this issue out for now. Please feel free to re-open it or raise a new one if you are still experiencing issues with the build.
