### ISSUE TITLE
Splitmuxsrc

### ISSUE THREAD

**Issue by compiaffe** [amzn/amazon-s3-gst-plugin#43]
Are there plans to support for a splitmuxsrc?

**Comment by russnic** [comment]
Hi compiaffe,

Unfortunately we do not have any plans to add support for splitmuxsrc.

However we do accept pull requests and will review as and when they're submitted.

Alternatively there is also [awss3hlssink](https://gstreamer.freedesktop.org/documentation/aws/awss3hlssink.html?gi-language=python#awss3hlssink-page) and [awss3sink](awss3sink) which are part of [gst-plugin-aws](https://crates.io/crates/gst-plugin-aws) which may suit your needs.

Kind regards,

russnic
