### ISSUE TITLE
aws-sdk-cpp Log interface did change - build error

### ISSUE THREAD

**Issue by thomas-roos** [amzn/amazon-s3-gst-plugin#44]
This change https://github.com/aws/aws-sdk-cpp/commit/9bee62c4a6b9e07f52b05186a51f3e38b1ec2d5a
is leading to this issue: 
[issue.txt](https://github.com/amzn/amazon-s3-gst-plugin/files/14746272/issue.txt)

**Comment by thomas-roos** [comment]
potential patch:
/home/ubuntu/data/yocto/yocto_master/meta-aws/recipes-multimedia/amazon-s3-gst-plugin/files/vaLog.txt

**Comment by russnic** [comment]
Hey Thomas,

I've submitted PR https://github.com/amzn/amazon-s3-gst-plugin/pull/46 with your suggested fix, thank you!

Kind regards,

russnic

**Comment by russnic** [comment]
Hey Thomas,

PR https://github.com/amzn/amazon-s3-gst-plugin/pull/46 has now been merged.

If you require anything further please re-open or create a new issue.

Kind regards,

russnic
