### ISSUE TITLE
Allow more modification of AWS::Client::Configuration

### ISSUE THREAD

**Issue by jhhurwitz** [amzn/amazon-s3-gst-plugin#9]
Hello,

I am hoping to use the amazon-s3-gst-plugin with a different backend then S3 (e.g. minio/ceph), which requires modifying the `Aws::Client::ClientConfiguration`, explicitly allowing changes like:

```
client_config.endpointOverride = Aws::String("ip:port");
client_config.scheme = Aws::Http::Scheme::HTTP;
client_config.verifySSL = false;
```
and
```
 _s3_client = std::unique_ptr<Aws::S3::S3Client>(new Aws::S3::S3Client(std::move(credentials_provider), client_config, Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never, false));
```

As far as I can tell, there isn't currently a great way to do this without just changing the source code. It would be great if there could be a way to modify these values at runtime. 

Happy to contribute if you feel this is valuable and not currently on the roadmap!

Thanks for the awesome plugin

**Comment by loganek** [comment]
Hi @jhhurwitz, I think the changes you propose make sense. I think it'd be good to expose `endpointOverride`, scheme,  `verifySSL` and payload signin policy as parameters to the element. 
I'm happy to review pull request if you are willing to contribute to the project :)

**Comment by violivei** [comment]
Closing it in favour of merged pull request.
